// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SwaggerWebProxy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Object containing string value
    /// </summary>
    public partial class ValueObj
    {
        /// <summary>
        /// Initializes a new instance of the ValueObj class.
        /// </summary>
        public ValueObj() { }

        /// <summary>
        /// Initializes a new instance of the ValueObj class.
        /// </summary>
        public ValueObj(string value = default(string))
        {
            Value = value;
        }

        /// <summary>
        /// string value
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

    }
}
